import "./globals.css";
import type { Metadata } from "next";
import { NavBar } from "@/components/NavBar";
import { Player } from "@/components/Player";

import { ViewportProvider } from "@/public/assets/viewportcontext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ViewportProvider>
          <NavBar />
          <Player />
          {children}
        </ViewportProvider>
      </body>
    </html>
  );
}
